-injars target/orderix-contract-event-library-0.0.1-SNAPSHOT.jar
-outjars target/orderix-contract-event-library-0.0.1-SNAPSHOT-obfuscated.jar
-dontwarn
-dontoptimize
-dontobfuscate
-keep public class com.orderix.** { *; }
