name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>guardsquare</id>
                <repositories>
                  <repository>
                    <id>guardsquare</id>
                    <url>https://maven.guardsquare.com</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>guardsquare</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Build and Obfuscate JAR
        run: mvn clean package -DskipTests

      - name: Upload obfuscated JAR
        uses: actions/upload-artifact@v4
        with:
          name: obfuscated-jar-${{ github.sha }}
          path: target/*-obfuscated.jar

  generate-docs:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Generate sources from Avro schema
        run: mvn compile -DskipTests

      - name: Generate Javadocs
        run: mvn javadoc:javadoc

      - name: Upload Javadocs
        uses: actions/upload-artifact@v4
        with:
          name: javadocs
          path: target/site/apidocs/

  deploy-docs:
    runs-on: ubuntu-latest
    needs: generate-docs

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Prepare branch
        run: |
          git fetch origin gh-pages || true
          git checkout --orphan gh-pages
          git rm -rf . || true

      - name: Download Javadocs
        uses: actions/download-artifact@v4
        with:
          name: javadocs
          path: .

      - name: Commit and push Javadocs
        run: |
          git add .
          git commit -m "Deploy Javadocs for ${{ github.sha }}" || echo "No changes to commit"
          git push --force origin HEAD:gh-pages

  deploy-package:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>guardsquare</id>
                <repositories>
                  <repository>
                    <id>guardsquare</id>
                    <url>https://maven.guardsquare.com</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>guardsquare</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Clear local Maven repo (optional)
        run: rm -rf ~/.m2/repository/com/orderix/

      - name: Deploy to GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
